apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          ports:
            - containerPort: 8080
            - containerPort: 6889
              protocol: TCP
            - containerPort: 6889
              protocol: UDP
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Asia/Kolkata
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "6881"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: tv
              mountPath: /tv
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 30
      volumes:
        - name: config
          hostPath:
            path: /root/.var/app/org.qbittorrent.qBittorrent/data
            type: DirectoryOrCreate
        - name: movies
          hostPath:
            path: /fs/media/movies
        - name: tv
          hostPath:
            path: /fs/media/tv
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30801
    - name: torrent-tcp
      port: 6889
      targetPort: 6889
      protocol: TCP
    - name: torrent-udp
      port: 6889
      targetPort: 6889
      protocol: UDP
