apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux-db
  template:
    metadata:
      labels:
        app: miniflux-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: miniflux-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: miniflux-config
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - miniflux
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: postgres-data
          hostPath:
            path: /fs/lab/data/miniflux/psql
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-db
spec:
  selector:
    app: miniflux-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
        - name: miniflux
          image: miniflux/miniflux:latest@sha256:02e50d5b277857e3600c14ec1a6a064a82320077914d8eb546691a5f4c1d406c
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: miniflux-secret
                  key: DATABASE_URL
            - name: RUN_MIGRATIONS
              valueFrom:
                configMapKeyRef:
                  name: miniflux-config
                  key: RUN_MIGRATIONS
            - name: CREATE_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: miniflux-config
                  key: CREATE_ADMIN
            - name: ADMIN_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: miniflux-config
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux-secret
                  key: ADMIN_PASSWORD
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: miniflux-config
                  key: DEBUG
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
spec:
  type: NodePort
  selector:
    app: miniflux
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30908
