apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
    spec:
      containers:
        - name: immich-redis
          image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: immich-redis
spec:
  selector:
    app: immich-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-database
  template:
    metadata:
      labels:
        app: immich-database
    spec:
      containers:
        - name: immich-database
          image: ghcr.io/immich-app/postgres:16-vectorchord0.4.3-pgvectors0.2.0@sha256:1a078b237c1d9b420b0ee59147386b4aa60d3a07a8e6a402fc84a57e41b043a4
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: DB_USERNAME
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: DB_DATABASE_NAME
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /fs/lab/data/immich/postgres
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: immich-database
spec:
  selector:
    app: immich-database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v2.3.1
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: TZ
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: ml-cache
              mountPath: /cache
      volumes:
        - name: ml-cache
          hostPath:
            path: /fs/lab/data/immich/cache
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
spec:
  selector:
    app: immich-machine-learning
  ports:
    - name: http
      port: 3003
      targetPort: 3003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v2.3.1
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: TZ
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: DB_USERNAME
            - name: DB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: DB_DATABASE_NAME
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: DB_HOSTNAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: DB_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: DB_PASSWORD
            - name: REDIS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: REDIS_HOSTNAME
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: REDIS_PORT
            - name: IMMICH_MACHINE_LEARNING_URL
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: IMMICH_MACHINE_LEARNING_URL
          ports:
            - containerPort: 2283
          volumeMounts:
            - name: upload
              mountPath: /usr/src/app/upload
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          livenessProbe:
            httpGet:
              path: /api/server/ping
              port: 2283
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              cpu: "2"
              memory: "4096Mi"
      volumes:
        - name: upload
          hostPath:
            path: /fs/lab/data/immich/media
            type: DirectoryOrCreate
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
spec:
  type: NodePort
  selector:
    app: immich-server
  ports:
    - name: http
      port: 2283
      targetPort: 2283
      nodePort: 32283
