apiVersion: v1
kind: Service
metadata:
  name: immich-server
spec:
  type: NodePort
  selector:
    app: immich-server
  ports:
    - name: http
      port: 2283
      targetPort: 2283
      nodePort: 32283
