apiVersion: v1
kind: Service
metadata:
  name: syncthing
spec:
  type: NodePort
  selector:
    app: syncthing
  ports:
    - name: webui
      port: 8384
      targetPort: 8384
      nodePort: 30084
    - name: sync-tcp
      port: 22000
      targetPort: 22000
      protocol: TCP
    - name: sync-udp
      port: 22000
      targetPort: 22000
      protocol: UDP
    - name: discovery
      port: 21027
      targetPort: 21027
      protocol: UDP
