apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          env:
           - name: PUID
             value: "0"
           - name: PGID
             value: "0"
          ports:
            - containerPort: 8096
            - containerPort: 8920
            - containerPort: 7359
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: tv
              mountPath: /tv
            - name: backup
              mountPath: /backup
            - name: dri
              mountPath: /dev/dri
          livenessProbe:
            httpGet:
              path: /
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: config
          hostPath:
            path: /fs/lab/data/jellyfin/config
            type: DirectoryOrCreate
        - name: movies
          hostPath:
            path: /fs/media/movies
        - name: tv
          hostPath:
            path: /fs/media/tv
        - name: backup
          hostPath:
            path: /fs/backups/cold/movies
        - name: dri
          hostPath:
            path: /dev/dri
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: NodePort
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      nodePort: 30896
    - name: https
      port: 8920
      targetPort: 8920
    - name: discovery-client
      port: 7359
      targetPort: 7359
      protocol: UDP
    - name: discovery-server
      port: 1900
      targetPort: 1900
      protocol: UDP
