apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: linuxserver/syncthing:latest
          ports:
            - containerPort: 8384
            - containerPort: 22000
              protocol: TCP
            - containerPort: 22000
              protocol: UDP
            - containerPort: 21027
              protocol: UDP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Asia/Kolkata
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 45
            periodSeconds: 30
      volumes:
        - name: config
          hostPath:
            path: /fs/lab/data/syncthing/config
            type: DirectoryOrCreate
        - name: data
          hostPath:
            path: /fs/lab/data/syncthing
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
spec:
  type: NodePort
  selector:
    app: syncthing
  ports:
    - name: webui
      port: 8384
      targetPort: 8384
      nodePort: 30084
    - name: sync-tcp
      port: 22000
      targetPort: 22000
      protocol: TCP
    - name: sync-udp
      port: 22000
      targetPort: 22000
      protocol: UDP
    - name: discovery
      port: 21027
      targetPort: 21027
      protocol: UDP
