apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty-drive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copyparty-drive
  template:
    metadata:
      labels:
        app: copyparty-drive
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: copyparty
          image: copyparty/ac:latest@sha256:e6ff5501752dc714473dcfe2da4eddb8d1fbf38b74573e59a0c812758272a9e5
          ports:
            - containerPort: 3923
          env:
            - name: LD_PRELOAD
              value: /usr/lib/libmimalloc-secure.so.NOPE
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: cfg
              mountPath: /cfg
            - name: drive
              mountPath: /drive
            - name: media
              mountPath: /media
            - name: downloads
              mountPath: /downloads
          livenessProbe:
            httpGet:
              path: /
              port: 3923
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3923
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: cfg
          hostPath:
            path: /fs/lab/data/copyparty/drive
            type: DirectoryOrCreate
        - name: drive
          hostPath:
            path: /fs/lab/data/copyparty/drive
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /fs/media
            type: Directory
        - name: downloads
          hostPath:
            path: /fs/downloads
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: copyparty-drive
spec:
  type: NodePort
  selector:
    app: copyparty-drive
  ports:
    - name: http
      port: 3923
      targetPort: 3923
      nodePort: 30924
