apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30801
    - name: torrent-tcp
      port: 6889
      targetPort: 6889
      protocol: TCP
    - name: torrent-udp
      port: 6889
      targetPort: 6889
      protocol: UDP
