apiVersion: v1
kind: Service
metadata:
  name: kakeibo
  namespace: default
spec:
  type: NodePort
  selector:
    app: kakeibo
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-server
  namespace: default
spec:
  selector:
    app: qdrant
  ports:
  - name: http
    port: 6333
    targetPort: 6333
  - name: grpc
    port: 6334
    targetPort: 6334
